name: Go

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Allow the action to request an ID token.
      contents: read # With no permissions, the ID token may be empty. Give it something.
    strategy:
      matrix:
        go-version: ["1.24.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run test
        run: go run ./run.go
      - name: Run bash
        run: ./run.sh
